### ISSUE TITLE
Input placeholder in Firefox is visible 

### ISSUE THREAD

**Issue by bigchimp** [tonystar/float-label-css#20]
The input placeholder is visible in Firefox 
![untitled](https://user-images.githubusercontent.com/585779/29482470-42a27dec-8457-11e7-8aa3-a3970c5d47e2.png)
when not in focus

**Comment by staticpo** [comment]
This issue is still occurring. Any updates?

**Comment by subhan-git** [comment]
try adding class `.has-float-label .form-control:placeholder-shown:not(:focus)::-moz-placeholder {opacity:0;}`

**Comment by jorgevazquezmeli** [comment]
Well, acording to https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-placeholder
The -moz-placeholder is in the process of being removed and Firefox 51 and up support the actual placeholder style.

**Comment by marsjaninzmarsa** [comment]
Should be resolved as outdated I believe, I cannot reproduce in current Firefox.

**Comment by liquidsunshine** [comment]
Still happens with both the Bootstrap 3 and Bootstrap 4 demo for me.  The no-dependencies demo works fine.
![firefox_2018-11-26_11-28-04](https://user-images.githubusercontent.com/1158592/49028673-f131bd00-f170-11e8-9e42-8089b4642106.png)

**Comment by marsjaninzmarsa** [comment]
Funny:
```  CSS
.form-control::-moz-placeholder {
  color: #999;
  opacity: 1;
}
.form-control:-ms-input-placeholder {
  color: #999;
}
.form-control::-webkit-input-placeholder {
  color: #999;
}
```
(bootstrap.css:2560)

**Comment by uschmidt** [comment]
Works also with additional

```
.form-control:not(:focus)::placeholder {
  opacity: 0;
}
```
